#!/bin/sh

#/home/gluex/Software/CentOS-7/build_scripts/gluex_env_version.csh /home/gluex/Software/CentOS-7/versions/version_master.xml
cp AnalyseRun.C AnalyseRun_Enhancement_Only.C
root -b -q -l "AnalyseRun_Enhancement_Only.C($1, $2, $3, $4, $5)"
sleep 10
echo "done"
